# Generated by Django 6.0.4 on 2026-04-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название продукта')),
                ('calories', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Калории на 100 г')),
                ('proteins', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Белки на 100 г')),
                ('fats', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Жиры на 100 г')),
                ('carbs', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Углеводы на 100 г')),
                ('is_custom', models.BooleanField(default=False, verbose_name='Пользовательский продукт')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['name'],
            },
        ),
    ]
