# Generated by Django 6.0.4 on 2026-05-03 00:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_waterentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_status',
            field=models.CharField(choices=[('active', 'Активный'), ('in_progress', 'Заполняется'), ('paused', 'Приостановлен'), ('needs_update', 'Требует обновления данных')], default='active', max_length=20, verbose_name='Статус профиля'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Текущий вес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], max_length=20, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height',
            field=models.PositiveIntegerField(verbose_name='Рост'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='target_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Целевой вес'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
